project_id = "dwliuzujgjglbkezqsls"

[functions.generate-campaign]
verify_jwt = false

[functions.improve-email]
verify_jwt = false

[functions.lemon-squeezy-webhook]
verify_jwt = false

[functions.translate-campaign]
verify_jwt = false

[functions.reset-monthly-credits]
verify_jwt = false

[functions.export-to-klaviyo]
verify_jwt = false
