project_id = "dwliuzujgjglbkezqsls"

[functions.generate-campaign]
verify_jwt = true

[functions.improve-email]
verify_jwt = true

[functions.lemon-squeezy-webhook]
verify_jwt = false

[functions.translate-campaign]
verify_jwt = true
